#!/usr/bin/env bash

##
##
##   https://github.com/babebort/software-updater/docs/ROADMAP.md
##
##


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
os=$(uname -s);

if [ "$os" = "Linux" ]; 
then
    read -p '# Is your OS Debian Based (Ubuntu, Linux Mint., Kali etc.)? Yes or No: ' answer
    answer=${answer^^}

    if [ "$answer" = "YES" ]; 
    then

        FILENAME="$DIR/ProtonPass.deb";    
        URL="https://proton.me/download/PassDesktop/linux/x64/ProtonPass.deb";

        echo "## Closing Proton Pass ...";
        for pid in $(pidof Proton\ Pass); do kill -9 $pid; done
        echo "## Proton Pass instance(s) closed.";
        if test -d "$INSTALLPATH"; then
            sudo rm -rf $INSTALLPATH;
            echo "## Removed last downloaded version.";
        fi
        if test -e "$FILENAME"; then
            rm $FILENAME;
            rm -rf $FOLDERNAME;
            echo "## Removed last downloaded version.";
        fi

        echo "## Downloading latest version of Proton Pass is starting...";
        wget -q --show-progress -O $FILENAME $URL;
        echo "## Downloading finished.";
        echo "## Installing...";
        sudo dpkg -i $FILENAME;
        echo "## Installation finished.";
    else
        FILENAME="$DIR/ProtonPass.rpm";    
        URL="https://proton.me/download/PassDesktop/linux/x64/ProtonPass.rpm";

        echo "## Closing Proton Pass ...";
        for pid in $(pidof Proton\ Pass); do kill -9 $pid; done
        echo "## Proton Pass instance(s) closed.";
        if test -d "$INSTALLPATH"; then
            sudo rm -rf $INSTALLPATH;
            echo "## Removed last installed version.";
        fi
        if test -e "$FILENAME"; then
            rm $FILENAME;
            rm -rf $FOLDERNAME;
            echo "## Removed last downloaded version.";
        fi

        echo "## Downloading latest version of Proton Pass is starting...";
        wget -q --show-progress -O $FILENAME $URL;
        echo "## Downloading finished.";
        echo "## Installing...";
        sudo rpm -ivh $FILENAME;
        echo "## Installation finished.";
    fi
else
    echo "## This script is only for Linux.";
    exit;
fi
